version: "3.8"

services:
  rpi-app:
    image: "${DOCKER_USERNAME}/my-rpi-gpio-app:latest"
    restart: always
    privileged: true
    volumes:
      - /dev:/dev
    environment:
      - GPIO_MODE=BCM
