name: Deploy to Raspberry Pi via SSH (Tailscale)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repository (optional, can be removed if not needed)
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Install & Authenticate Tailscale
      - name: Install & Authenticate Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}

      # ✅ Setup SSH Key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "100.106.32.37" >> ~/.ssh/known_hosts

      # ✅ Deploy using Docker Image
      - name: Deploy Code
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ameen@${{ secrets.RPI_HOST }} << 'EOF'
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            export DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/my-rpi-gpio-app:latest

            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
            fi

            # Login to Docker Hub (if required)
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Pull the latest Docker image
            docker pull $DOCKER_IMAGE

            # Stop and remove any existing container
            docker stop rpi-app || true
            docker rm rpi-app || true

            # Run the new container
            docker run -d --name rpi-app --restart unless-stopped --privileged $DOCKER_IMAGE
          EOF
