name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, arm64]  # This makes it run on your Pi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Raspberry Pi
        run: |
          echo "Connected to Raspberry Pi via Tailscale!"
          docker pull your-docker-image
          docker run -d --privileged --name my-gpio-app your-docker-image
