name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.RPI_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Raspberry Pi
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ameen@${{ secrets.RPI_HOST }} << 'EOF'
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

            # Ensure the project directory exists
            mkdir -p /home/ameen/project
            cd /home/ameen/project

            # Clone or update the repo
            if [ ! -d ".git" ]; then
              git clone https://github.com/ameen-syed/project_main.git .
            else
              git pull origin main
            fi

            # Install Docker & Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null; then
              sudo apt update
              sudo apt install -y docker-compose
            fi

            # Start the application
            docker-compose up -d --build
          EOF
