name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug SSH Connection Variables
        run: |
          echo "Checking SSH connectivity..."
          echo "RPI_HOST: ${{ secrets.RPI_HOST }}"
          echo "RPI_USER: ${{ secrets.RPI_USER }}"
          
      - name: Test SSH Connection
        run: nc -zv ${{ secrets.SSH_HOST }} 22
  
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_PASSWORD }}
          port: 22
          timeout: 120s
          script_stop: true
          script: ls -all

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          password: ${{ secrets.RPI_PASSWORD }}
          port: 22
          timeout: 120s
          script: |
            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-rpi-gpio-app:latest

            echo "Waiting for image download to complete..."
            until docker images | grep -q "${{ secrets.DOCKER_USERNAME }}/my-rpi-gpio-app"; do
              echo "Waiting..."
              sleep 5
            done

            echo "Stopping old container..."
            docker stop my-gpio-app || true
            docker rm my-gpio-app || true

            echo "Running new container..."
            docker run -d --privileged --name my-gpio-app ${{ secrets.DOCKER_USERNAME }}/my-rpi-gpio-app
          debug: true
          
