name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.RPI_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Raspberry Pi
        run: |
          ssh pi@${{ secrets.SSH_HOSTNAME }} "cd /path/to/your/app && git pull && docker-compose up -d"
